### PR TITLE
GHA: add dbt Cloud alternative

### PR DESCRIPTION
**Pull request by jaceksan**

### CODE REVIEW

**Comment by jaceksan** [comment]
WARNING: some executions of dbt models in this merge request are slower than average!Threshold=20%

| Model ID                                         |   Last duration(s) |   Average duration(s) |   Difference(%) | Degradation   |
|--------------------------------------------------|--------------------|-----------------------|-----------------|---------------|
| model.cicd_demo.aircraft                         |               1.4  |                  1.57 |          -10.63 | False         |
| model.cicd_demo.aircraft_models                  |               1.5  |                  1.62 |           -7.52 | False         |
| model.cicd_demo.airports                         |               1.41 |                  1.58 |          -11.14 | False         |
| model.cicd_demo.ambient_temperature              |               1.26 |                  1.44 |          -12.23 | False         |
| model.cicd_demo.carriers                         |               1.32 |                  1.34 |           -1.44 | False         |
| model.cicd_demo.census                           |               1.21 |                  1.28 |           -5.73 | False         |
| model.cicd_demo.census_by_country                |               1.32 |                  1.37 |           -3.36 | False         |
| model.cicd_demo.commits                          |               2.46 |                  2.21 |           11.15 | False         |
| model.cicd_demo.commits_extract_json             |               2.45 |                  2.39 |            2.35 | False         |
| model.cicd_demo.customer                         |               1.24 |                  1.32 |           -6.52 | False         |
| model.cicd_demo.eshop_customers                  |               1.1  |                  1.29 |          -14.69 | False         |
| model.cicd_demo.flights                          |               2.32 |                  2.12 |            9.58 | False         |
| model.cicd_demo.home_rentals                     |               1.24 |                  1.28 |           -2.55 | False         |
| model.cicd_demo.house_property_sales_time_series |               1.63 |                  1.26 |           28.68 | True          |
| model.cicd_demo.mall_customers                   |               1.16 |                  1.22 |           -5.04 | False         |
| model.cicd_demo.monthlyinventory                 |               1.25 |                  1.34 |           -6.81 | False         |
| model.cicd_demo.order_lines                      |               1.97 |                  1.79 |           10.15 | False         |
| model.cicd_demo.orders                           |               1.35 |                  1.4  |           -3.59 | False         |
| model.cicd_demo.product                          |               1.29 |                  1.25 |            3.82 | False         |
| model.cicd_demo.pull_requests                    |               3.46 |                  2.53 |           36.47 | True          |
| model.cicd_demo.pull_requests_extract_json       |               3.22 |                  2.32 |           38.68 | True          |
| model.cicd_demo.repos                            |               1.54 |                  1.44 |            7.09 | False         |
| model.cicd_demo.returns                          |               1.59 |                  1.36 |           17.5  | False         |
| model.cicd_demo.telco_customer_churn             |               1.54 |                  1.4  |            9.91 | False         |

**Comment by jaceksan** [comment]
**WARNING:** some executions of dbt models in this merge request are slower than average!Threshold=20%

| Model ID                                         |   Last duration(s) |   Average duration(s) |   Difference(%) | Degradation   |
|--------------------------------------------------|--------------------|-----------------------|-----------------|---------------|
| model.cicd_demo.aircraft                         |               1.4  |                  1.57 |          -10.63 | False         |
| model.cicd_demo.aircraft_models                  |               1.5  |                  1.62 |           -7.52 | False         |
| model.cicd_demo.airports                         |               1.41 |                  1.58 |          -11.14 | False         |
| model.cicd_demo.ambient_temperature              |               1.26 |                  1.44 |          -12.23 | False         |
| model.cicd_demo.carriers                         |               1.32 |                  1.34 |           -1.44 | False         |
| model.cicd_demo.census                           |               1.21 |                  1.28 |           -5.73 | False         |
| model.cicd_demo.census_by_country                |               1.32 |                  1.37 |           -3.36 | False         |
| model.cicd_demo.commits                          |               2.46 |                  2.21 |           11.15 | False         |
| model.cicd_demo.commits_extract_json             |               2.45 |                  2.39 |            2.35 | False         |
| model.cicd_demo.customer                         |               1.24 |                  1.32 |           -6.52 | False         |
| model.cicd_demo.eshop_customers                  |               1.1  |                  1.29 |          -14.69 | False         |
| model.cicd_demo.flights                          |               2.32 |                  2.12 |            9.58 | False         |
| model.cicd_demo.home_rentals                     |               1.24 |                  1.28 |           -2.55 | False         |
| model.cicd_demo.house_property_sales_time_series |               1.63 |                  1.26 |           28.68 | True          |
| model.cicd_demo.mall_customers                   |               1.16 |                  1.22 |           -5.04 | False         |
| model.cicd_demo.monthlyinventory                 |               1.25 |                  1.34 |           -6.81 | False         |
| model.cicd_demo.order_lines                      |               1.97 |                  1.79 |           10.15 | False         |
| model.cicd_demo.orders                           |               1.35 |                  1.4  |           -3.59 | False         |
| model.cicd_demo.product                          |               1.29 |                  1.25 |            3.82 | False         |
| model.cicd_demo.pull_requests                    |               3.46 |                  2.53 |           36.47 | True          |
| model.cicd_demo.pull_requests_extract_json       |               3.22 |                  2.32 |           38.68 | True          |
| model.cicd_demo.repos                            |               1.54 |                  1.44 |            7.09 | False         |
| model.cicd_demo.returns                          |               1.59 |                  1.36 |           17.5  | False         |
| model.cicd_demo.telco_customer_churn             |               1.54 |                  1.4  |            9.91 | False         |

**Comment by jaceksan** [comment]
@jaceksan **WARNING:** some executions of dbt models in this merge request are slower than average! Threshold = 20%

| Model ID                                         |   Last duration(s) |   Average duration(s) |   Difference(%) | Degradation   |
|--------------------------------------------------|--------------------|-----------------------|-----------------|---------------|
| model.cicd_demo.aircraft                         |               1.4  |                  1.57 |          -10.63 | False         |
| model.cicd_demo.aircraft_models                  |               1.5  |                  1.62 |           -7.52 | False         |
| model.cicd_demo.airports                         |               1.41 |                  1.58 |          -11.14 | False         |
| model.cicd_demo.ambient_temperature              |               1.26 |                  1.44 |          -12.23 | False         |
| model.cicd_demo.carriers                         |               1.32 |                  1.34 |           -1.44 | False         |
| model.cicd_demo.census                           |               1.21 |                  1.28 |           -5.73 | False         |
| model.cicd_demo.census_by_country                |               1.32 |                  1.37 |           -3.36 | False         |
| model.cicd_demo.commits                          |               2.46 |                  2.21 |           11.15 | False         |
| model.cicd_demo.commits_extract_json             |               2.45 |                  2.39 |            2.35 | False         |
| model.cicd_demo.customer                         |               1.24 |                  1.32 |           -6.52 | False         |
| model.cicd_demo.eshop_customers                  |               1.1  |                  1.29 |          -14.69 | False         |
| model.cicd_demo.flights                          |               2.32 |                  2.12 |            9.58 | False         |
| model.cicd_demo.home_rentals                     |               1.24 |                  1.28 |           -2.55 | False         |
| model.cicd_demo.house_property_sales_time_series |               1.63 |                  1.26 |           28.68 | True          |
| model.cicd_demo.mall_customers                   |               1.16 |                  1.22 |           -5.04 | False         |
| model.cicd_demo.monthlyinventory                 |               1.25 |                  1.34 |           -6.81 | False         |
| model.cicd_demo.order_lines                      |               1.97 |                  1.79 |           10.15 | False         |
| model.cicd_demo.orders                           |               1.35 |                  1.4  |           -3.59 | False         |
| model.cicd_demo.product                          |               1.29 |                  1.25 |            3.82 | False         |
| model.cicd_demo.pull_requests                    |               3.46 |                  2.53 |           36.47 | True          |
| model.cicd_demo.pull_requests_extract_json       |               3.22 |                  2.32 |           38.68 | True          |
| model.cicd_demo.repos                            |               1.54 |                  1.44 |            7.09 | False         |
| model.cicd_demo.returns                          |               1.59 |                  1.36 |           17.5  | False         |
| model.cicd_demo.telco_customer_churn             |               1.54 |                  1.4  |            9.91 | False         |

**Comment by jaceksan** [comment]
@jaceksan **WARNING:** some executions of dbt models in this merge request are slower than average! Threshold = 20%

| Model ID                                         |   Last duration(s) |   Average duration(s) |   Difference(%) | Degradation   |
|--------------------------------------------------|--------------------|-----------------------|-----------------|---------------|
| model.cicd_demo.aircraft                         |               1.4  |                  1.57 |          -10.63 | False         |
| model.cicd_demo.aircraft_models                  |               1.5  |                  1.62 |           -7.52 | False         |
| model.cicd_demo.airports                         |               1.41 |                  1.58 |          -11.14 | False         |
| model.cicd_demo.ambient_temperature              |               1.26 |                  1.44 |          -12.23 | False         |
| model.cicd_demo.carriers                         |               1.32 |                  1.34 |           -1.44 | False         |
| model.cicd_demo.census                           |               1.21 |                  1.28 |           -5.73 | False         |
| model.cicd_demo.census_by_country                |               1.32 |                  1.37 |           -3.36 | False         |
| model.cicd_demo.commits                          |               2.46 |                  2.21 |           11.15 | False         |
| model.cicd_demo.commits_extract_json             |               2.45 |                  2.39 |            2.35 | False         |
| model.cicd_demo.customer                         |               1.24 |                  1.32 |           -6.52 | False         |
| model.cicd_demo.eshop_customers                  |               1.1  |                  1.29 |          -14.69 | False         |
| model.cicd_demo.flights                          |               2.32 |                  2.12 |            9.58 | False         |
| model.cicd_demo.home_rentals                     |               1.24 |                  1.28 |           -2.55 | False         |
| model.cicd_demo.house_property_sales_time_series |               1.63 |                  1.26 |           28.68 | True          |
| model.cicd_demo.mall_customers                   |               1.16 |                  1.22 |           -5.04 | False         |
| model.cicd_demo.monthlyinventory                 |               1.25 |                  1.34 |           -6.81 | False         |
| model.cicd_demo.order_lines                      |               1.97 |                  1.79 |           10.15 | False         |
| model.cicd_demo.orders                           |               1.35 |                  1.4  |           -3.59 | False         |
| model.cicd_demo.product                          |               1.29 |                  1.25 |            3.82 | False         |
| model.cicd_demo.pull_requests                    |               3.46 |                  2.53 |           36.47 | True          |
| model.cicd_demo.pull_requests_extract_json       |               3.22 |                  2.32 |           38.68 | True          |
| model.cicd_demo.repos                            |               1.54 |                  1.44 |            7.09 | False         |
| model.cicd_demo.returns                          |               1.59 |                  1.36 |           17.5  | False         |
| model.cicd_demo.telco_customer_churn             |               1.54 |                  1.4  |            9.91 | False         |

**Comment by jaceksan** [comment]
@jaceksan **WARNING:** some executions of dbt models in this merge request are slower than average! Threshold = 20%

| Model ID                                         |   Last duration(s) |   Average duration(s) |   Difference(%) | Degradation   |
|--------------------------------------------------|--------------------|-----------------------|-----------------|---------------|
| model.cicd_demo.aircraft                         |               1.86 |                  3.46 |          -46.33 | False         |
| model.cicd_demo.aircraft_models                  |               2.11 |                  3.65 |          -42.1  | False         |
| model.cicd_demo.airports                         |               2.11 |                  3.59 |          -41.17 | False         |
| model.cicd_demo.ambient_temperature              |               1.85 |                  3.41 |          -45.88 | False         |
| model.cicd_demo.carriers                         |               1.57 |                  1.41 |           11.3  | False         |
| model.cicd_demo.census                           |               1.54 |                  1.42 |            8.43 | False         |
| model.cicd_demo.census_by_country                |               1.59 |                  1.46 |            8.74 | False         |
| model.cicd_demo.commits                          |               2.42 |                  2.39 |            1.29 | False         |
| model.cicd_demo.commits_extract_json             |               2.9  |                  2.74 |            5.7  | False         |
| model.cicd_demo.customer                         |               1.41 |                  1.19 |           18.69 | False         |
| model.cicd_demo.eshop_customers                  |               1.42 |                  1.36 |            4.71 | False         |
| model.cicd_demo.flights                          |               2.1  |                  1.99 |            5.54 | False         |
| model.cicd_demo.home_rentals                     |               1.45 |                  1.37 |            6.34 | False         |
| model.cicd_demo.house_property_sales_time_series |               1.35 |                  1.32 |            2.25 | False         |
| model.cicd_demo.mall_customers                   |               1.26 |                  1.3  |           -2.56 | False         |
| model.cicd_demo.monthlyinventory                 |               1.52 |                  1.33 |           14.35 | False         |
| model.cicd_demo.order_lines                      |               2    |                  1.58 |           26.37 | True          |
| model.cicd_demo.orders                           |               1.57 |                  1.31 |           20.4  | True          |
| model.cicd_demo.product                          |               1.31 |                  1.11 |           18.26 | False         |
| model.cicd_demo.pull_requests                    |               2.56 |                  2.55 |            0.3  | False         |
| model.cicd_demo.pull_requests_extract_json       |               2.51 |                  2.51 |            0.11 | False         |
| model.cicd_demo.repos                            |               1.34 |                  1.63 |          -17.71 | False         |
| model.cicd_demo.returns                          |               1.42 |                  1.16 |           22.33 | True          |
| model.cicd_demo.telco_customer_churn             |               1.57 |                  1.49 |            4.88 | False         |

**Review by Mara3l — APPROVED** [review]

**Pull request merged**
